### ISSUE TITLE
Unable to see the Shadow Text properties

### ISSUE THREAD

**Issue by adxworld** [bigmountainstudio/DesignableX#5]
I saw the tutorial, pretty amazing stuff. But I am unable to find the shadow text properties for yhe UIlabelX. Is it deleted now?

**Comment by auflint** [comment]
Same question.

**Comment by bigmountainstudio** [comment]
Sorry for such a late response on this! I updated the UILabelX file and the project to show a preview of the label with the shadow applied. Also updated project to Swift 4.
